# retrieves all scaled model id's in the database

# optional: the name of a model set that id's should be retrieved for
# used to only retrieve a subset of models, pre-specified in the database
# leave empty to get all models
string model_set

---

# the outcome of the query
DatabaseReturnCode return_code

# the actual model ids
int32[] scaled_model_ids